# Generated by Django 4.1 on 2022-09-12 22:33

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('gid', models.CharField(default=backend.models.get_rand, max_length=20, primary_key=True, serialize=False, verbose_name='Group ID')),
                ('faculty', models.CharField(max_length=10, verbose_name='Faculty name')),
                ('gnum', models.SmallIntegerField(verbose_name='Group number')),
            ],
            options={
                'verbose_name': 'Group',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Pair name')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=10, verbose_name='day')),
                ('number', models.SmallIntegerField(verbose_name='Pair number')),
                ('week_type', models.CharField(choices=[('odd', 'Odd'), ('even', 'Even')], default='odd', max_length=4, verbose_name='Type of week')),
                ('start_time', models.CharField(choices=[('09:00', '09:00 |1| 2-3курс'), ('10:50', '10:50 |2| 2-3курс'), ('12:40', '12:40 |3| 2-3курс'), ('14:10', '14:10 |4| 2-3курс'), ('15:40', '15:40 |5| 2-3курс'), ('17:10', '17:10 |6| 2-3курс'), ('09:30', '09:30 |1| 1-4курс'), ('11:20', '11:20 |2| 1-4курс'), ('13:10', '13:10 |3| 1-4курс'), ('14:40', '14:40 |4| 1-4курс'), ('16:10', '16:10 |5| 1-4курс'), ('17:40', '17:40 |6| 1-4курс')], max_length=5, verbose_name='Start pair')),
                ('end_time', models.CharField(choices=[('10:20', '10:20 |1| 2-3курс'), ('12:10', '12:10 |2| 2-3курс'), ('14:00', '14:00 |3| 2-3курс'), ('15:30', '15:30 |4| 2-3курс'), ('17:00', '17:00 |5| 2-3курс'), ('18:30', '18:30 |6| 2-3курс'), ('10:50', '10:50 |1| 1-4курс'), ('12:40', '12:40 |2| 1-4курс'), ('14:30', '14:30 |3| 1-4курс'), ('16:00', '16:00 |4| 1-4курс'), ('17:30', '17:30 |5| 1-4курс'), ('19:00', '19:00 |6| 1-4курс')], max_length=5, verbose_name='End pair')),
                ('classroom', models.CharField(max_length=200, verbose_name='Classroom')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.groups')),
            ],
            options={
                'verbose_name': 'Schedule',
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('user_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='User chat id')),
                ('username', models.CharField(max_length=32, null=True)),
                ('notification', models.BooleanField(default=True, null=True, verbose_name='Notifications for the user')),
                ('is_admin', models.BooleanField(default=False, null=True)),
                ('is_moderator', models.BooleanField(default=False, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.groups')),
            ],
            options={
                'verbose_name': 'User profile',
            },
        ),
        migrations.AddConstraint(
            model_name='groups',
            constraint=models.UniqueConstraint(fields=('faculty', 'gnum'), name='unique_group'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('group_id', 'day', 'number', 'week_type'), name='unique_sdl'),
        ),
    ]
